#!/usr/bin/env ruby

require 'json'
require 'colorize'

id =''
state_file = ARGV[0]
id = ARGV[1] if ARGV[1]

# puts 'state file: ' + state_file
# puts 'id to find: ' + id

unless File.file?(state_file)
  puts 'no file found: ' + state_file
  puts 'Usage: terrorm_get_ids <statefile> <resource>'
end

data = JSON.parse(File.read(state_file))
# puts data['modules'].class.to_s
# puts data['modules'].length.to_s

puts



data['modules'].each_index do |ele|
#  puts data['modules'].count
#  puts ele.to_s

  data['modules'][ele]['resources'].each_key do |key|
    if ( id == '' || id == key )
      puts '['.green + key.green + '][primary][id]'.green
      puts data['modules'][ele]['resources'][key]['primary']['id'].cyan
    end
    if ( id == key )
      puts JSON.pretty_generate(data['modules'][ele]['resources'][key]).magenta
    end
  end


end

# data['modules'][-1]['outputs'].each_key do |key|
#   if ( id == '' || id == key )
#     puts '['.green + key.green + '][primary][id]'.green
#     puts data['modules'][-1]['resources'][key]['primary']['id'].cyan
#   end
#   if ( id == key )
#     puts JSON.pretty_generate(data['modules'][-1]['resources'][key]).magenta
#   end
# end

puts 

